/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface _SERVICE {
  'addWarningSensor' : ActorMethod<[bigint, string], undefined>,
  'getAllHazardStatuses' : ActorMethod<
    [],
    {
      'bio' : string,
      'gas' : string,
      'fire' : string,
      'electrical' : string,
      'radiation' : string,
    }
  >,
  'getBioStatus' : ActorMethod<[], string>,
  'getCommunicationInfo' : ActorMethod<[], [boolean, string, string, boolean]>,
  'getElectricalStatus' : ActorMethod<[], string>,
  'getEnvProtectionInfo' : ActorMethod<[], [boolean, bigint, bigint, string]>,
  'getFireStatus' : ActorMethod<[], string>,
  'getGasStatus' : ActorMethod<[], string>,
  'getHazardData' : ActorMethod<[], [bigint, bigint, bigint, bigint, bigint]>,
  'getLifeSupportInfo' : ActorMethod<
    [],
    [boolean, bigint, bigint, bigint, string]
  >,
  'getModuleStates' : ActorMethod<
    [],
    {
      'helmet' : boolean,
      'moduleSync' : boolean,
      'defibrillator' : boolean,
      'respirator' : boolean,
      'longJump' : boolean,
      'radiationShield' : boolean,
      'shieldBoost' : boolean,
      'hazardSystem' : boolean,
      'flashlight' : boolean,
    }
  >,
  'getPowerInfo' : ActorMethod<[], [boolean, bigint, bigint, bigint]>,
  'getRadiationStatus' : ActorMethod<[], string>,
  'getStats' : ActorMethod<[], [bigint, bigint, bigint, bigint, bigint]>,
  'getSuitState' : ActorMethod<[], Array<[string, string]>>,
  'getSystemState' : ActorMethod<[], [boolean, bigint, string]>,
  'getSystemStatus' : ActorMethod<[], string>,
  'getWarningSensors' : ActorMethod<[], Array<[bigint, string]>>,
  'removeWarningSensor' : ActorMethod<[bigint], undefined>,
  'setErrorState' : ActorMethod<[string], undefined>,
  'setSuitState' : ActorMethod<[string, string], undefined>,
  'setTemperature' : ActorMethod<[bigint], undefined>,
  'switchHudDisplay' : ActorMethod<[string], undefined>,
  'toggleHazard' : ActorMethod<[string, bigint], undefined>,
  'toggleLifeSupportSystem' : ActorMethod<[], undefined>,
  'toggleModule' : ActorMethod<[string], undefined>,
  'updateStats' : ActorMethod<[string, bigint], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];