/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ModuleToggles = IDL.Record({
  'helmet' : IDL.Bool,
  'moduleSync' : IDL.Bool,
  'defibrillator' : IDL.Bool,
  'advancedMedical' : IDL.Bool,
  'respirator' : IDL.Bool,
  'longJump' : IDL.Bool,
  'radiationShield' : IDL.Bool,
  'shieldBoost' : IDL.Bool,
  'hazardSystem' : IDL.Bool,
  'flashlight' : IDL.Bool,
});

export const idlService = IDL.Service({
  'addWarningSensor' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'getAllHazardStatuses' : IDL.Func(
      [],
      [
        IDL.Record({
          'bio' : IDL.Text,
          'gas' : IDL.Text,
          'fire' : IDL.Text,
          'electrical' : IDL.Text,
          'radiation' : IDL.Text,
        }),
      ],
      [],
    ),
  'getBioStatus' : IDL.Func([], [IDL.Text], []),
  'getCommunicationInfo' : IDL.Func(
      [],
      [IDL.Bool, IDL.Text, IDL.Text, IDL.Bool],
      [],
    ),
  'getElectricalStatus' : IDL.Func([], [IDL.Text], []),
  'getEnvProtectionInfo' : IDL.Func(
      [],
      [IDL.Bool, IDL.Nat, IDL.Nat, IDL.Text],
      [],
    ),
  'getFireStatus' : IDL.Func([], [IDL.Text], []),
  'getGasStatus' : IDL.Func([], [IDL.Text], []),
  'getHazardData' : IDL.Func(
      [],
      [IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat],
      [],
    ),
  'getLifeSupportInfo' : IDL.Func(
      [],
      [IDL.Bool, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Text],
      [],
    ),
  'getModuleStates' : IDL.Func([], [ModuleToggles], ['query']),
  'getPowerInfo' : IDL.Func([], [IDL.Bool, IDL.Nat, IDL.Nat, IDL.Nat], []),
  'getRadiationStatus' : IDL.Func([], [IDL.Text], []),
  'getStats' : IDL.Func([], [IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat], []),
  'getSuitState' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text))],
      ['query'],
    ),
  'getSystemState' : IDL.Func([], [IDL.Bool, IDL.Nat, IDL.Text], []),
  'getSystemStatus' : IDL.Func([], [IDL.Text], ['query']),
  'getWarningSensors' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Text))],
      ['query'],
    ),
  'removeWarningSensor' : IDL.Func([IDL.Nat], [], []),
  'setErrorState' : IDL.Func([IDL.Text], [], []),
  'setSuitState' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'setTemperature' : IDL.Func([IDL.Nat], [], []),
  'switchHudDisplay' : IDL.Func([IDL.Text], [], []),
  'toggleHazard' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'toggleLifeSupportSystem' : IDL.Func([], [], []),
  'toggleModule' : IDL.Func([IDL.Text], [], []),
  'updateStats' : IDL.Func([IDL.Text, IDL.Nat], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ModuleToggles = IDL.Record({
    'helmet' : IDL.Bool,
    'moduleSync' : IDL.Bool,
    'defibrillator' : IDL.Bool,
    'advancedMedical' : IDL.Bool,
    'respirator' : IDL.Bool,
    'longJump' : IDL.Bool,
    'radiationShield' : IDL.Bool,
    'shieldBoost' : IDL.Bool,
    'hazardSystem' : IDL.Bool,
    'flashlight' : IDL.Bool,
  });
  
  return IDL.Service({
    'addWarningSensor' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'getAllHazardStatuses' : IDL.Func(
        [],
        [
          IDL.Record({
            'bio' : IDL.Text,
            'gas' : IDL.Text,
            'fire' : IDL.Text,
            'electrical' : IDL.Text,
            'radiation' : IDL.Text,
          }),
        ],
        [],
      ),
    'getBioStatus' : IDL.Func([], [IDL.Text], []),
    'getCommunicationInfo' : IDL.Func(
        [],
        [IDL.Bool, IDL.Text, IDL.Text, IDL.Bool],
        [],
      ),
    'getElectricalStatus' : IDL.Func([], [IDL.Text], []),
    'getEnvProtectionInfo' : IDL.Func(
        [],
        [IDL.Bool, IDL.Nat, IDL.Nat, IDL.Text],
        [],
      ),
    'getFireStatus' : IDL.Func([], [IDL.Text], []),
    'getGasStatus' : IDL.Func([], [IDL.Text], []),
    'getHazardData' : IDL.Func(
        [],
        [IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat],
        [],
      ),
    'getLifeSupportInfo' : IDL.Func(
        [],
        [IDL.Bool, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Text],
        [],
      ),
    'getModuleStates' : IDL.Func([], [ModuleToggles], ['query']),
    'getPowerInfo' : IDL.Func([], [IDL.Bool, IDL.Nat, IDL.Nat, IDL.Nat], []),
    'getRadiationStatus' : IDL.Func([], [IDL.Text], []),
    'getStats' : IDL.Func(
        [],
        [IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat],
        [],
      ),
    'getSuitState' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text))],
        ['query'],
      ),
    'getSystemState' : IDL.Func([], [IDL.Bool, IDL.Nat, IDL.Text], []),
    'getSystemStatus' : IDL.Func([], [IDL.Text], ['query']),
    'getWarningSensors' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Text))],
        ['query'],
      ),
    'removeWarningSensor' : IDL.Func([IDL.Nat], [], []),
    'setErrorState' : IDL.Func([IDL.Text], [], []),
    'setSuitState' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'setTemperature' : IDL.Func([IDL.Nat], [], []),
    'switchHudDisplay' : IDL.Func([IDL.Text], [], []),
    'toggleHazard' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'toggleLifeSupportSystem' : IDL.Func([], [], []),
    'toggleModule' : IDL.Func([IDL.Text], [], []),
    'updateStats' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  });
};

export const init = ({ IDL }) => { return []; };