/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface ModuleToggles {
    helmet: boolean;
    moduleSync: boolean;
    defibrillator: boolean;
    advancedMedical: boolean;
    respirator: boolean;
    longJump: boolean;
    radiationShield: boolean;
    shieldBoost: boolean;
    hazardSystem: boolean;
    flashlight: boolean;
}
export interface backendInterface {
    addWarningSensor(id: bigint, location: string): Promise<void>;
    getAllHazardStatuses(): Promise<{
        bio: string;
        gas: string;
        fire: string;
        electrical: string;
        radiation: string;
    }>;
    getBioStatus(): Promise<string>;
    getCommunicationInfo(): Promise<[boolean, string, string, boolean]>;
    getElectricalStatus(): Promise<string>;
    getEnvProtectionInfo(): Promise<[boolean, bigint, bigint, string]>;
    getFireStatus(): Promise<string>;
    getGasStatus(): Promise<string>;
    getHazardData(): Promise<[bigint, bigint, bigint, bigint, bigint]>;
    getLifeSupportInfo(): Promise<[boolean, bigint, bigint, bigint, string]>;
    getModuleStates(): Promise<ModuleToggles>;
    getPowerInfo(): Promise<[boolean, bigint, bigint, bigint]>;
    getRadiationStatus(): Promise<string>;
    getStats(): Promise<[bigint, bigint, bigint, bigint, bigint]>;
    getSuitState(): Promise<Array<[string, string]>>;
    getSystemState(): Promise<[boolean, bigint, string]>;
    getSystemStatus(): Promise<string>;
    getWarningSensors(): Promise<Array<[bigint, string]>>;
    removeWarningSensor(id: bigint): Promise<void>;
    setErrorState(errorType: string): Promise<void>;
    setSuitState(key: string, value: string): Promise<void>;
    setTemperature(tempVal: bigint): Promise<void>;
    switchHudDisplay(_mode: string): Promise<void>;
    toggleHazard(hazardType: string, level: bigint): Promise<void>;
    toggleLifeSupportSystem(): Promise<void>;
    toggleModule(moduleName: string): Promise<void>;
    updateStats(stat: string, value: bigint): Promise<void>;
}
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addWarningSensor(arg0: bigint, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addWarningSensor(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addWarningSensor(arg0, arg1);
            return result;
        }
    }
    async getAllHazardStatuses(): Promise<{
        bio: string;
        gas: string;
        fire: string;
        electrical: string;
        radiation: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllHazardStatuses();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllHazardStatuses();
            return result;
        }
    }
    async getBioStatus(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getBioStatus();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBioStatus();
            return result;
        }
    }
    async getCommunicationInfo(): Promise<[boolean, string, string, boolean]> {
        if (this.processError) {
            try {
                const result = await this.actor.getCommunicationInfo();
                return [
                    result[0],
                    result[1],
                    result[2],
                    result[3]
                ];
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCommunicationInfo();
            return [
                result[0],
                result[1],
                result[2],
                result[3]
            ];
        }
    }
    async getElectricalStatus(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getElectricalStatus();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getElectricalStatus();
            return result;
        }
    }
    async getEnvProtectionInfo(): Promise<[boolean, bigint, bigint, string]> {
        if (this.processError) {
            try {
                const result = await this.actor.getEnvProtectionInfo();
                return [
                    result[0],
                    result[1],
                    result[2],
                    result[3]
                ];
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEnvProtectionInfo();
            return [
                result[0],
                result[1],
                result[2],
                result[3]
            ];
        }
    }
    async getFireStatus(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getFireStatus();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFireStatus();
            return result;
        }
    }
    async getGasStatus(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getGasStatus();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGasStatus();
            return result;
        }
    }
    async getHazardData(): Promise<[bigint, bigint, bigint, bigint, bigint]> {
        if (this.processError) {
            try {
                const result = await this.actor.getHazardData();
                return [
                    result[0],
                    result[1],
                    result[2],
                    result[3],
                    result[4]
                ];
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getHazardData();
            return [
                result[0],
                result[1],
                result[2],
                result[3],
                result[4]
            ];
        }
    }
    async getLifeSupportInfo(): Promise<[boolean, bigint, bigint, bigint, string]> {
        if (this.processError) {
            try {
                const result = await this.actor.getLifeSupportInfo();
                return [
                    result[0],
                    result[1],
                    result[2],
                    result[3],
                    result[4]
                ];
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLifeSupportInfo();
            return [
                result[0],
                result[1],
                result[2],
                result[3],
                result[4]
            ];
        }
    }
    async getModuleStates(): Promise<ModuleToggles> {
        if (this.processError) {
            try {
                const result = await this.actor.getModuleStates();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getModuleStates();
            return result;
        }
    }
    async getPowerInfo(): Promise<[boolean, bigint, bigint, bigint]> {
        if (this.processError) {
            try {
                const result = await this.actor.getPowerInfo();
                return [
                    result[0],
                    result[1],
                    result[2],
                    result[3]
                ];
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPowerInfo();
            return [
                result[0],
                result[1],
                result[2],
                result[3]
            ];
        }
    }
    async getRadiationStatus(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getRadiationStatus();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRadiationStatus();
            return result;
        }
    }
    async getStats(): Promise<[bigint, bigint, bigint, bigint, bigint]> {
        if (this.processError) {
            try {
                const result = await this.actor.getStats();
                return [
                    result[0],
                    result[1],
                    result[2],
                    result[3],
                    result[4]
                ];
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStats();
            return [
                result[0],
                result[1],
                result[2],
                result[3],
                result[4]
            ];
        }
    }
    async getSuitState(): Promise<Array<[string, string]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSuitState();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSuitState();
            return result;
        }
    }
    async getSystemState(): Promise<[boolean, bigint, string]> {
        if (this.processError) {
            try {
                const result = await this.actor.getSystemState();
                return [
                    result[0],
                    result[1],
                    result[2]
                ];
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSystemState();
            return [
                result[0],
                result[1],
                result[2]
            ];
        }
    }
    async getSystemStatus(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getSystemStatus();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSystemStatus();
            return result;
        }
    }
    async getWarningSensors(): Promise<Array<[bigint, string]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getWarningSensors();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWarningSensors();
            return result;
        }
    }
    async removeWarningSensor(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeWarningSensor(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeWarningSensor(arg0);
            return result;
        }
    }
    async setErrorState(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setErrorState(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setErrorState(arg0);
            return result;
        }
    }
    async setSuitState(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setSuitState(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setSuitState(arg0, arg1);
            return result;
        }
    }
    async setTemperature(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setTemperature(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setTemperature(arg0);
            return result;
        }
    }
    async switchHudDisplay(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.switchHudDisplay(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.switchHudDisplay(arg0);
            return result;
        }
    }
    async toggleHazard(arg0: string, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.toggleHazard(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.toggleHazard(arg0, arg1);
            return result;
        }
    }
    async toggleLifeSupportSystem(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.toggleLifeSupportSystem();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.toggleLifeSupportSystem();
            return result;
        }
    }
    async toggleModule(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.toggleModule(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.toggleModule(arg0);
            return result;
        }
    }
    async updateStats(arg0: string, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateStats(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateStats(arg0, arg1);
            return result;
        }
    }
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
